FROM openjdk

# # Set the working directory inside the container
# WORKDIR /app

# # Copy the current directory contents into the container at /app
# COPY . /app

# # Specify the JAR file to run the application
# ARG JAR_FILE=target

# # Add the JAR file to the container
# ADD ${JAR_FILE} app.jar

# # Expose port 8080 to the outside world (adjust based on your application)
# EXPOSE 8080

# # Run the application
# ENTRYPOINT ["java","-jar","app.jar"]
